### ISSUE TITLE
Bad notification for startForeground

### ISSUE THREAD

**Issue by bradseefeld** [transistorsoft/nativescript-background-geolocation-lt#118]
## Your Environment
* Plugin version: 1.9.0-beta.3
* Platform: iOS or Android: Android
* OS version: 6
* Device manufacturer / model: Generic
* Nativescript version (`tns info`):
```
$ tns info
✔ Getting NativeScript components versions information...
✔ Component nativescript has 4.1.2 version and is up to date.
✔ Component tns-core-modules has 4.1.0 version and is up to date.
✔ Component tns-android has 4.1.3 version and is up to date.
✔ Component tns-ios has 4.1.3 version and is up to date.
```
* Plugin config

## Expected Behavior
No exception

## Actual Behavior
```
System.err: android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x6a color=0x00000000 vis=PRIVATE)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
System.err: 	at android.os.Looper.loop(Looper.java:164)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
JS: [Sentry - Android] Exeption on capture:  Error: Cannot convert object to Lio/sentry/event/Event; at index 0
JS: [Sentry - Android] Exeption on capture:  Error: Cannot convert object to Lio/sentry/event/Event; at index 0
ActivityManager: Process com.dispatchbot.driver (pid 14318) has died: fore TOP 
ActivityManager: setHasOverlayUi called on unknown pid: 14318
```

This is received immediately after accepting the location tracking permission

Downgrading to 1.9.0-beta.1 or 1.8.0 without any other changes does not have this issue.

**Comment by christocracy** [comment]
Duplicate #117
