### ISSUE TITLE
Demo does not work with NativeScript v5.3.4

### ISSUE THREAD

**Issue by brentfraser** [transistorsoft/nativescript-background-geolocation-lt#148]
I'm new to Node.js and NativeScript, so this may be simple misunderstanding.

## Your Environment
* This Plugin version: 1.9.1
* Target Platform: Android
* Dev OS version: Windows 7
* Node.js version: v10.15.3
* Target Device manufacturer / model: Samsung S4
* Nativescript version (`tns info`): 5.3.4
* Plugin config
√ Component nativescript has 5.3.4 version and is up to date.
√ Component tns-core-modules has 5.3.1 version and is up to date.
√ Component tns-android has 5.3.1 version and is up to date.
√ Component tns-ios has 5.3.1 version and is up to date.
## Expected Behavior

By following the Demo instructions in the readme.md, I should have a working demo app.
## Actual Behavior

When issuing the npm command:
`npm run setup`
an error is generated:
`npm ERR! missing script: setup`

so this instruction should be removed or fixed.

Ignoring the error and continuing to follow the instructions to `npm run demo.android` gives messages about "short imports" being deprecated:
`Please note that short imports are deprecated since NativeScript 5.2.0`
it continues to build and install the app on my emulator, but fails with:
`
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
...
`

## Steps to Reproduce

1.  Install latest node
2.  Install latest NativeScript
3.  Follow instructions in this plugin's readme.md to run demo app.

## Context

I am trying to see if this plugin works with the current version of NativeScript

## Debug logs

An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4556)
	at android.app.ActivityThread.access$1500(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
	at com.tns.Module.bootstrapApp(Module.java:311)
	at com.tns.Runtime.run(Runtime.java:615)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
	... 9 more
Caused by: com.tns.NativeScriptException: Failed to find module: "./", relative to: app//
	at com.tns.Module.resolvePathHelper(Module.java:146)
	at com.tns.Module.bootstrapApp(Module.java:309)
	... 13 more

**Comment by christocracy** [comment]
I’m ceasing support for NativeScript.

You can use the plugin with Cordova/Ionic, React Native or Flutter

**Comment by brentfraser** [comment]
Ok, you may want to put a note at the top of the readme.md so others don't spend time on this.

**Comment by christocracy** [comment]
Note is coming.  It’s a recent decision.

**Comment by brentfraser** [comment]
Great.  I had started to look into Cordova, but set it aside when I found it didn't have the ability to get GPS positions in the background.  I'll have a look at the Cordova plugin.  Thanks!

**Comment by christocracy** [comment]
It is the same underlying native libs in all versions of the plugin.  

My personal favorite is Flutter.
