### ISSUE TITLE
Navigating to map-page breaks http callback

### ISSUE THREAD

**Issue by 3rror404** [transistorsoft/nativescript-background-geolocation-lt#32]
I have been seeing this behaviour in my own app and have finally worked out how to reproduce in yours.

If the app loads a page before `map-page` (a login page for example) and then  `frameModule.topmost().navigate()` is used to navigate to the `map-page`, the `onHttp` callback will not fire.

The sync succeeds and I see the following in terminal:
```
11-21 12:05:20.799  8999  9065 D TSLocationManager:   ℹ️  No JSON found in server response
JS: sync SUCCESS
```

yet the http callback doesn't fire.

app.ts
```
//application.start({ moduleName: "./pages/map/map-page" });
application.start({ moduleName: "./pages/login/login" });
```

login.xml
```
<Page loaded="onLoaded">
    <Label text="Login page" />
</Page>
```

login.js
```
var frameModule = require("ui/frame");

exports.onLoaded = function(args) {

    var nav = {
        moduleName: "pages/map/map-page",
        clearHistory: true,
        transition: {
            name: "fade",
            duration: 380,
            curve: "easeIn"
        }
    };
    frameModule.topmost().navigate(nav);
}
```

config (whatever the demo app default is plus...)
```
autoSync: false,
batchSync: true,
maxBatchSize: -1,
url: **API_URL**,
extras : {
    journeyID: 0,
    vehicleID: 0
}
```

Strangely, if the app is terminated and reopened the callback will start to work.

On a separate note, I often see in the console "ℹ️  No JSON found in server response" yet there clearly is JSON in the response. Any idea why this may be?

```
JS: [js] http:  {"status":200,"responseText":"[{\"JourneyID\":4487,\"EventCount\":2,\"Status\":\"SUCCESS\",\"Message\":\"CREATED\"}]"}
11-21 10:00:32.499 29074 29130 D TSLocationManager:   ℹ️  No JSON found in server response
```

**Comment by 3rror404** [comment]
Same problem with the [nativescript-2.4.0 branch](https://github.com/transistorsoft/nativescript-background-geolocation-lt/tree/nativescript-2.4.0)

**Comment by christocracy** [comment]
Don't worry about `No JSON found in server response`.  The plugin attempts to decode the JSON but doesn't do anything with it.  It's for a feature I have in mind for the future, where the server could potentially send commands to the plugin in the HTTP response.  Ignore.

**Comment by christocracy** [comment]
I implemented you fake LoginPage and I still fail to see an issue here.

**Comment by 3rror404** [comment]
That's very strange. I can reproduce this 100% of the time in the simulator and on a real device.

Is there any chance you could run this fork just so I know we are doing exactly the same thing?

https://github.com/3rror404/nativescript-background-geolocation-lt .

I'll email you the URL to insert in the config.

Also, with the latest version I'm getting crashes when tapping 'btnPace` sometimes.

**Comment by christocracy** [comment]
Ok, I reproduced that issue.  Try building latest from master.

**Comment by 3rror404** [comment]
Thanks Chris. That looks to have solved the http callback problem but terminating the app whilst tracking causes it to crash on resume:

```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.transistorsoft.backgroundgeolocation.nativescript/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: Cannot read property 'getIntent' of undefined
File: "/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/frame/frame.js, line: 685, column: 18

StackTrace: 
	Frame: function:'BackgroundGeolocation.getAdapter', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/nativescript-background-geolocation-lt/background-geolocation.js', line: 426, column: 144
	Frame: function:'BackgroundGeolocation.init', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/nativescript-background-geolocation-lt/background-geolocation.js', line: 29, column: 14
	Frame: function:'', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/nativescript-background-geolocation-lt/background-geolocation.js', line: 13, column: 27
	Frame: function:'Observable.notify', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/data/observable/observable.js', line: 149, column: 23
	Frame: function:'onActivityCreated', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/application/application.js', line: 19, column: 24
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/frame/frame.js', line: 685, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/frame/activity.js', line: 13, column: 25


	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3319)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
	at android.app.ActivityThread.access$1100(ActivityThread.java:229)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7325)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: Cannot read property 'getIntent' of undefined
File: "/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/frame/frame.js, line: 685, column: 18

StackTrace: 
	Frame: function:'BackgroundGeolocation.getAdapter', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/nativescript-background-geolocation-lt/background-geolocation.js', line: 426, column: 144
	Frame: function:'BackgroundGeolocation.init', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/nativescript-background-geolocation-lt/background-geolocation.js', line: 29, column: 14
	Frame: function:'', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/nativescript-background-geolocation-lt/background-geolocation.js', line: 13, column: 27
	Frame: function:'Observable.notify', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/data/observable/observable.js', line: 149, column: 23
	Frame: function:'onActivityCreated', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/application/application.js', line: 19, column: 24
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/frame/frame.js', line: 685, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'/data/data/com.transistorsoft.backgroundgeolocation.nativescript/files/app/tns_modules/ui/frame/activity.js', line: 13, column: 25


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
	at com.tns.Runtime.callJSMethod(Runtime.java:895)
	at com.tns.Runtime.callJSMethod(Runtime.java:879)
	at com.tns.Runtime.callJSMethod(Runtime.java:871)
	at com.tns.NativeScriptActivity.onCreate(android.app.Activity.java)
	at android.app.Activity.performCreate(Activity.java:6904)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
	... 9 more
```

**Comment by christocracy** [comment]
re-install from master again.

**Comment by 3rror404** [comment]
Thanks Chris. This now looks to be working correctly.
